export { default as logoVB } from "./logoVB.jpg";
export { default as slider1 } from "./slider1.jpg";
export { default as slider2 } from "./slider2.jpg";
export { default as main1 } from "./main_1.jpg";
export { default as lDistancia } from "./LargaDistancia.png";
export { default as traccion } from "./traccion.png";
export { default as ejeLibre } from "./EjeLibre.png";
export { default as todaPosicion } from "./todaPosicion.png";
export { default as Urbano } from "./Urbano.png";
export { default as Regional } from "./Regional.png";
export { default as Recoleccion } from "./Recoleccion.png";
export { default as On_Off } from "./On_Off.png";
export { default as off_road } from "./off_road.png";
export { default as UAP2 } from "./UAP2_FULTECH.png";
export { default as R4200} from "./R4200.png";
export { default as BRX2 } from "./BRX2.png";
export { default as B104 } from "./B104.png";
export { default as UAP } from "./UAP.png";
export { default as RTP } from "./RTP.png";
export { default as B268 } from "./B268.png";
export { default as B163 } from "./B163.png";
export { default as WIDE } from "./WIDE_BASE_RIB.png";
export { default as BZE2 } from "./BZE2.png";
export { default as BDV } from "./BDV.png";
export { default as METROMAX } from "./METROMAX_RIB.png";
export { default as BRM } from "./BRM.png";
// export { default as UAP2 } from "./UAP2_FULTECH.png";
// export { default as UAP2 } from "./UAP2_FULTECH.png";
// export { default as UAP2 } from "./UAP2_FULTECH.png";
// export { default as UAP2 } from "./UAP2_FULTECH.png";
// export { default as UAP2 } from "./UAP2_FULTECH.png";
// export { default as UAP2 } from "./UAP2_FULTECH.png";
// export { default as UAP2 } from "./UAP2_FULTECH.png";
// export { default as UAP2 } from "./UAP2_FULTECH.png";
// export { default as UAP2 } from "./UAP2_FULTECH.png";
